config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    resource :session, only: %i[new create destroy]

    resources :users, only: %i[new create edit update]

    resources :questions do
      resources :answers, except: %i[new show]
    end

    # resources :pages, only: %i[show]
    get "all" => "questions#all"

    root 'pages#index'
    get "up" => "rails/health#show", as: :rails_health_check
  end
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  belongs_to :user

  validates :title, presence: true, length: {minimum: 2}
  validates :body, presence: true, length: {minimum: 2}

  def formatted_created_at
    # I18n.l(created_at, :format => '%d %B %Y, %H:%M')
    I18n.l(created_at, format: :long)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question!, only: %i[show destroy edit update]

  def show
    @answer = @question.answers.build
    @allanswers = @question.answers.all
    @answers = @question.answers.order(created_at: :desc).page(params[:page]).per(7)
    # Answer.where(question: @question).order(created_at: :desc)
  end

  def destroy
    @question.destroy
    flash[:success] = t('.success')
    redirect_to questions_path
  end

  def edit
  end

  def update
    if !current_user.present?
      flash[:success] = "Изменять без авторизации нельзя!"
      redirect_to questions_path
    elsif current_user.id == @question.user_id
      if @question.update question_params
        flash[:success] = t('.success')
        redirect_to questions_path
        # redirect_to questions_path(anchor: "question-#{@question.id}")
      else
        render :edit
      end
    else
      flash[:success] = "Изменять чужой вопрос нельзя!"
      redirect_to questions_path
    end
  end

  def index
    @questions = Question.where(user_id: current_user.id).order(created_at: :desc).page(params[:page]).per(7)
  end

  def all
    if current_user.present?
      @questions = Question.where(
        "title LIKE ?", "%#{params[:search]}%").where(
          "user_id != ?", current_user.id).order(created_at: :desc).page(params[:page]).per(7)
    else
      @questions = Question.where(
        "title LIKE ?", "%#{params[:search]}%").order(created_at: :desc).page(params[:page]).per(7)
    end
  end

  def new
    @question = Question.new
  end

  def create
    if !current_user.present?
      flash[:success] = "Сначала авторизуйтесь!"
      redirect_to questions_path
    else
      @question = current_user.questions.build question_params
      if @question.save
        flash[:success] = t('.success')
        redirect_to questions_path
      else
        render :new
      end
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end

  def set_question!
    @question = Question.find params[:id]
  end

  def check_user!
    if current_user.present?
      render 
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= render 'shared/errors', object: @question %>

<%= form_with model: @question do |f| %>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :title %>
    </div>

    <div class="col-sm-10">
      <%= f.text_field :title, placeholder: 'Title', class: 'form-control' %>
    </div>
  </div>

  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :body %>
    </div>

    <div class="col-sm-10">
      <%= f.text_area :body, class: 'form-control' %>
    </div>
  </div>

  <%= f.submit t('global.button.submit'), class: 'btn btn-primary' %>
<% end %>

app/views/questions/_question.html.erb
<article class="card mt-3 shadow" id="question-<%= question.id %>">
  
  <section class="card-header">
    <%# <%= question.user.gravatar % > %>
    <%= question.user.name %>
  </section>
  
  <div class="card-body">
    <h4><%= question.title %></h2>

    <section class="card-text">
      <time datetime="<%= question.formatted_created_at %>">
        <small><%= question.formatted_created_at %></small>
      </time>

      <p class="my-2">
        <%= truncate strip_tags(question.body), length: 150, omission: t('global.text.omission') %>
      </p>
    </section>
    <div class="btn-group">
      <%= link_to t('global.button.show'), question_path(question), class: 'btn btn-primary' %> 
      <% if current_user.present? %>
      <% if current_user.id == question.user_id %>
        <%= link_to t('global.button.edit'), edit_question_path(question), class: 'btn btn-secondary' %>
        <%= button_to t('global.button.delete'), question_path(question), class: 'btn btn-danger',
          method: :delete, data: {turbo_confirm: t('global.dialog.you_sure')} %>
      <% end %>
      <% end %>
    </div>
  </div>
</article>

app/views/questions/all.html.erb
<% provide :page_title, t('.title') %>
<% currently_at t('menu.all') %>

<h1 class="mb-4"><%= t('.title') %></h1>

<%= form_tag(all_path, method: "get") do %>
    <div class="col-sm-10 mb-2">
      <%= text_field_tag :search, params[:search],
      placeholder: "Search for title", class: 'form-control' %>
    </div>

  <%= submit_tag "Search", class: 'btn btn-primary btn-lg' %>
<% end %>
<%# <%= link_to t('.new'), new_question_path, class: 'btn btn-primary btn-lg' % > %>
<%= paginate @questions %>

<%= render @questions %>

<%= paginate @questions %>

app/views/questions/edit.html.erb
<% provide :page_title, t('.title') %>
<% currently_at t('menu.questions') %>

<h1 class="mb-4"><%= t('.title') %></h1>

<%= render 'form' %>

app/views/questions/index.html.erb
<% provide :page_title, t('.title') %>
<% currently_at t('menu.questions') %>

<h1 class="mb-4"><%= t('.title') %></h1>

<%= link_to t('.new'), new_question_path, class: 'btn btn-primary btn-lg' %>
<%= paginate @questions %>

<%= render @questions %>

<%= paginate @questions %>

app/views/questions/new.html.erb
<% provide :page_title, t('.title') %>
<% currently_at t('menu.questions') %>

<h1 class="mb-4"><%= t('.title') %></h1>

<%= render 'form' %>

app/views/questions/show.html.erb
<% provide :page_title, @question.title %>
<% currently_at t('menu.questions') %>

<section class="card-header">
  <%# <%= question.user.gravatar % > %>
  <%= @question.user.name %>
</section>

<h1 class="mb-4"><%= @question.title %></h1>

<time datetime="<%= @question.formatted_created_at %>">
  <%= @question.formatted_created_at %>
</time>

<div class="lead my-3">
  <%= sanitize @question.body %>
</div>

<% if current_user.present? %>
<% if current_user.id == @question.user_id %>
  <div class="btn-group">
    <%= link_to t('global.button.show'), question_path(@question), class: 'btn btn-primary' %> 
    <%= link_to t('global.button.edit'), edit_question_path(@question), class: 'btn btn-secondary' %>
    <%= button_to t('global.button.delete'), question_path(@question), class: 'btn btn-danger',
      method: :delete, data: {confirm: t('global.dialog.you_sure')} %>
  </div>
<% end %>
<% end %>

<hr class="my-3">

<% if current_user.present? %>
  <h2 class="mb-3"><%= t('.write_answer') %></h2>
  <%= render 'answers/form' %>
<% end %>

<h2 class="mt-5"><%= t('.answers') %></h2>

<% if @allanswers.count > 7 %>
  <%= paginate @answers %>
<% end %>

<%= render partial: 'answers/answer', collection: @answers,
  as: :answer, locals: {question: @question} %>

<% if @allanswers.count > 7 %>
  <%= paginate @answers %> 
<% end %>