config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    resource :session, only: %i[new create destroy]

    resources :users, only: %i[new create edit update]

    resources :questions do
      resources :answers, except: %i[new show]
    end

    # resources :pages, only: %i[show]
    get "all" => "questions#all"

    root 'pages#index'
    get "up" => "rails/health#show", as: :rails_health_check
  end
end

app/views/shared/_errors.html.erb
<% if object.errors.full_messages.any? %>
  <div class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_menu.html.erb
<%= provide :main_menu do %>
  <header class="p-3 bg-dark text-white">
    <div class="container">
      <nav class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><%= nav_tab t('menu.home'), root_path,
            class: 'nav-link px-2', current_page: current_page %></li>
          <% if user_signed_in? %>
          <li><%= nav_tab t('menu.questions'), questions_path,
            class: 'nav-link px-2', current_page: current_page %></li>
          <% end %>
          <li><%= nav_tab t('menu.all'), all_path,
            class: 'nav-link px-2', current_page: current_page %></li>
        </ul>

        <ul class="nav col-12 col-lg-auto mb-2 mb-md-0">

          <div class="dropdown show">
            <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= t I18n.locale %>
            </a>

            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <% I18n.available_locales.each do |locale| %>
                
                <% if I18n.locale == locale %>
                  <%= tag.span t(locale), class: 'dropdown-item' %>
                <% else %>

                  <%= link_to t(locale), url_for(params.to_unsafe_h.merge(locale: locale)),
                    class: 'dropdown-item' %>
                <% end %>
                
              <% end %>
            </div>
          </div>
        </ul>

        <ul class="nav col-12 col-lg-auto mb-2 mb-md-0">
          <% if user_signed_in? %>
            <div class="dropdown show">
              <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= current_user.name %>
              </a>

              <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                <%= link_to t('menu.edit_profile'), edit_user_path(current_user),
                      class: 'dropdown-item' %>
          
                <hr class="dropdown-divider">

                <%= button_to t('menu.log_out'), session_path,
                      class: 'dropdown-item', method: :delete, data: {turbo_confirm: t('global.dialog.you_sure')} %>
              </div>
            </div>
          <% else %>
            <li><%= nav_tab t('menu.sign_up'), new_user_path,
              class: 'nav-link px-2', current_page: current_page %></li>

            <li><%= nav_tab t('menu.log_in'), new_session_path,
              class: 'nav-link px-2', current_page: current_page %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </header>
<% end %>