config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    resource :session, only: %i[new create destroy]

    resources :users, only: %i[new create edit update]

    resources :questions do
      resources :answers, except: %i[new show]
    end

    # resources :pages, only: %i[show]
    get "all" => "questions#all"

    root 'pages#index'
    get "up" => "rails/health#show", as: :rails_health_check
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user

  validates :body, presence: true, length: {minimum: 2}

  def formatted_created_at
    I18n.l(created_at, format: :long)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
    before_action :set_question!
    before_action :set_answer!, except: :create
  
    def update
      if @answer.update answer_update_params
        flash[:success] = t('.success')
        redirect_to question_path(@question, anchor: "answer-#{@answer.id}")
      else
        render :edit
      end
    end
  
    def edit
    end
  
    def create
      @answer = @question.answers.build answer_create_params
  
      if @answer.save
        flash[:success] = t('.success')
        redirect_to question_path(@question)
      else
        @allanswers = @question.answers.all
        @answers = @question.answers.order created_at: :desc
        render 'questions/show'
      end
    end
  
    def destroy
      @answer.destroy
      flash[:success] = t('.success')
      redirect_to question_path(@question)
    end
  
    private
  
    def answer_create_params
      params.require(:answer).permit(:body).merge(user_id: current_user.id)
    end

    def answer_update_params
      params.require(:answer).permit(:body)
    end
  
    def set_question!
      @question = Question.find params[:question_id]
    end
  
    def set_answer!
      @answer = @question.answers.find params[:id]
    end
  end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.erb
<article class="mb-3 card" id="answer-<%= answer.id %>">
  <section class="card-header">
    <%# <%= question.user.gravatar % > %>
    <%= answer.user.name %>
  </section>
  <div class="card-body">
    <section class="card-text">
      <small><time datetime="<%= answer.formatted_created_at %>">
        <%= answer.formatted_created_at %>
      </time></small>

      <div class="mt-2 mb-3">
        <%= sanitize answer.body %>
      </div>
    </section>
    <% if current_user.present? %>
    <% if current_user.id == answer.user_id %>
    <div class="btn-group">
      <%= link_to t('global.button.edit_answer'), edit_question_answer_path(question, answer), 
        class: 'btn btn-info btn-sm' %>
      <%= button_to t('global.button.delete'), question_answer_path(question, answer),
      class: 'btn btn-danger btn-sm',
        method: :delete, data: {turbo_confirm: t('global.dialog.you_sure')} %>
    </div>
    <% end %>
    <% end %>
  </div>
</article>

app/views/answers/_form.html.erb
<%= render 'shared/errors', object: @answer %>

<%= form_with model: [@question, @answer] do |f| %>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :body %>
    </div>

    <div class="col-sm-10">
      <%= f.text_area :body, class: 'form-control' %>
    </div>
  </div>

  <%= f.submit t('global.button.submit'), class: 'btn btn-primary' %>
<% end %>

app/views/answers/edit.html.erb
<% provide :page_title, t('.title') %>
<% currently_at t('menu.questions') %>

<h1><%= t('.title') %></h1>

<%= render 'form' %>